using System;

namespace ProHauler.Core.Models
{
    /// <summary>
    /// Represents a completed driving trip with performance metrics and statistics.
    /// A trip is defined as a continuous driving session from start to stop.
    /// </summary>
    public class Trip
    {
        /// <summary>
        /// Gets or sets the unique identifier for the trip.
        /// Auto-generated by the database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the trip start timestamp.
        /// Recorded when the vehicle begins moving (speed > 0).
        /// </summary>
        public DateTime StartTime { get; set; }

        /// <summary>
        /// Gets or sets the trip end timestamp.
        /// Recorded when the vehicle stops for more than 5 minutes or application closes.
        /// </summary>
        public DateTime EndTime { get; set; }

        /// <summary>
        /// Gets or sets the trip duration in minutes.
        /// Calculated as the difference between EndTime and StartTime.
        /// </summary>
        public float DurationMinutes { get; set; }

        /// <summary>
        /// Gets or sets the total distance traveled in miles.
        /// Accumulated from telemetry position changes or odometer readings.
        /// </summary>
        public float DistanceMiles { get; set; }

        /// <summary>
        /// Gets or sets the smoothness score for the trip (0-100%).
        /// Final smoothness score at trip end.
        /// </summary>
        public float SmoothnessScore { get; set; }

        /// <summary>
        /// Gets or sets the fuel efficiency in miles per gallon (MPG).
        /// Calculated from total distance divided by total fuel consumed.
        /// </summary>
        public float FuelEfficiencyMPG { get; set; }

        /// <summary>
        /// Gets or sets the speed compliance percentage (0-100%).
        /// Percentage of time spent at or below the speed limit.
        /// </summary>
        public float SpeedCompliancePercent { get; set; }

        /// <summary>
        /// Gets or sets the safety score for the trip (0-100%).
        /// Measures proper use of signals, lights, brakes, and other safety practices.
        /// </summary>
        public float SafetyScore { get; set; }

        /// <summary>
        /// Gets or sets the overall performance letter grade (A+ to F).
        /// Calculated from the average of all performance scores.
        /// </summary>
        public string OverallGrade { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the average speed in miles per hour.
        /// Calculated from total distance divided by total time.
        /// </summary>
        public float AverageSpeed { get; set; }

        /// <summary>
        /// Gets or sets the total fuel consumed in gallons.
        /// Tracked from fuel level changes during the trip.
        /// </summary>
        public float FuelConsumed { get; set; }
    }
}
